// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Fri May 09 00:54:44 2025

MAR MAR_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.Lm(Lm_sig) ,	// input  Lm_sig
	.SELECT(SELECT_sig) ,	// input  SELECT_sig
	.A(A_sig) ,	// input [3:0] A_sig
	.D(D_sig) ,	// input [3:0] D_sig
	.Out(Out_sig) 	// output [3:0] Out_sig
);

