// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Fri May 09 00:52:28 2025

RAM RAM_inst
(
	.addr(addr_sig) ,	// input [3:0] addr_sig
	.data_in(data_in_sig) ,	// input [7:0] data_in_sig
	.run_prog(run_prog_sig) ,	// input  run_prog_sig
	.ce(ce_sig) ,	// input  ce_sig
	.leitura_escrita(leitura_escrita_sig) ,	// input  leitura_escrita_sig
	.data_out(data_out_sig) 	// output [7:0] data_out_sig
);

